apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-production
  namespace: argocd # This is where your Argo CD instance runs
spec:
  project: default
  source:
    repoURL: https://github.com/PacoZG/devops-with-kubernetes-2025
    targetRevision: "[0-9]*.[0-9]*"
    path: project/deploy/kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
