apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-files-claim
  namespace: exercises
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
