import 'dotenv/config'

const { IMAGE_FILE_PATH, TIMESTAMP_FILE_PATH, PORT, POSTGRES_HOST, POSTGRES_PASSWORD } = process.env

console.debug('[SERVER]: Postgres config', {
  POSTGRES_HOST,
})

export { IMAGE_FILE_PATH, TIMESTAMP_FILE_PATH, PORT, POSTGRES_HOST, POSTGRES_PASSWORD }
