version: '3.9'

services:
  writer:
    image: hash-generator
    container_name: hash-generator
    build:
      context: ./log_output
      dockerfile: Dockerfile.generator
    environment:
      - GENERATOR_PORT=3002
      - HASH_FILE_PATH=shared/files/hash.txt
    ports:
      - 3002:3002
    volumes:
      - ./shared/files:/usr/src/app/shared/files

  reader:
    image: hash-reader
    container_name: hash-reader
    build:
      context: ./log_output
      dockerfile: Dockerfile.reader
    environment:
      - HASH_FILE_PATH=shared/files/hash.txt
      - PING_SERVER_URL=http://pingpong:8000
      - READER_PORT=3001
      - MESSAGE=hello world
      - INFORMATION_FILE_PATH=shared/files/information.txt
    ports:
      - 3001:3001
    volumes:
      - ./shared/files:/usr/src/app/shared/files

  pingpong:
    image: pingpong
    container_name: pingpong
    build:
      context: ./pingpong
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - COUNT_FILE_PATH=shared/files/count.txt
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - 8000:8000
    volumes:
      - ./shared/files:/usr/src/app/shared/files

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
