version: '3.9'

services:
  log-output:
    image: log-output
    container_name: log-output
    build:
      context: ./log_output
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001
  pingpong:
    image: pingpong
    container_name: pingpong
    build:
      context: ./pingpong
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    ports:
      - 8000:8000
