apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: log-output-files-claim
        - name: reader-files
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: hash-generator
          image: sirpacoder/hash-generator:v3.2
          imagePullPolicy: Always
          env:
            - name: GENERATOR_PORT
              value: "3002"
            - name: HASH_FILE_PATH
              value: "/usr/src/app/shared/files/hash.txt"
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/shared/files
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        - name: hash-reader
          image: sirpacoder/hash-reader:v3.2
          imagePullPolicy: Always
          env:
            - name: READER_PORT
              value: "3001"
            - name: HASH_FILE_PATH
              value: "/usr/src/app/shared/files/hash.txt"
            - name: INFORMATION_FILE_PATH
              value: /usr/src/app/reader/info/information.txt
            - name: PING_SERVER_URL
              value: http://pingpong-svc:80
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/shared/files
            - name: reader-files
              mountPath: /usr/src/app/reader/info
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
