apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: log-output-health-check-policy
  namespace: exercises
spec:
  targetRef:
    group: ""
    kind: Service
    name: log-output-svc
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: pingpong-health-check-policy
  namespace: exercises
spec:
  targetRef:
    group: ""
    kind: Service
    name: pingpong-svc
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /
