apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-files-claim
  namespace: main
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-files-claim
  namespace: main
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
