# 1. Define the StorageClass for manual provisioning of local volumes.
# This StorageClass tells Kubernetes how to handle PVs with 'manual' class.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner # Indicates static provisioning
volumeBindingMode: WaitForFirstConsumer # Recommended for local volumes to ensure node affinity is respected
reclaimPolicy: Retain # Or Delete, depending on your data retention policy
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingpong-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube/pingpong # Use a distinct path for this PV
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-output-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube/log-output # Use a distinct path for this PV
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
