apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong-svc
spec:
  template:
    metadata:
      labels:
        app: pingpong
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: pingpong
          image: sirpacoder/pingpong:v5.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: postgres-svc
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: pingpong-secret
