apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - 00-pingpong.yaml
  - 01-log_output.yaml
  - 02-configMap.yaml
  - 03-postgres.yaml
  - 04-ingress.yaml
#  - analysisTemplate.yaml
images:
  - name: GENERATOR/IMAGE
    newName: sirpacoder/hash-generator
    newTag: v4.1
  - name: READER/IMAGE
    newName: sirpacoder/hash-reader
    newTag: v4.1
  - name: PINGPONG/IMAGE
    newName: sirpacoder/pingpong
    newTag: v4.1
