version: '3.9'

services:
  client:
    image: client
    container_name: project-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - REACT_APP_SERVER_URL=http://localhost:3001
    ports:
      - 3000:3000
  server:
    image: server
    container_name: project-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - IMAGE_FILE_PATH="./shared/files/image.jpg"
      - TIMESTAMP_FILE_PATH="./shared/files/timestamp.txt"
    volumes:
      - ./shared/files:/usr/src/app/shared/files
    ports:
      - 3001:3001
