apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dep
  namespace: project
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: sirpacoder/client:v3.5
          imagePullPolicy: Always
          env:
            - name: REACT_APP_SERVER_URL
              value: ""
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
