apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: project-files-claim
      containers:
        - name: server
          image: sirpacoder/server:v3.5
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 3001
          env:
            - name: PORT
              value: "3001"
            - name: IMAGE_FILE_PATH
              value: "files/image.jpg"
            - name: TIMESTAMP_FILE_PATH
              value: "files/timestamp.txt"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map-variables
                  key: postgres-host
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-secrets
                  key: postgres-password
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '516Mi'
              cpu: '500m'
---

apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
