apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-client.yaml
  - 01-server.yaml
  - 02-postgres.yaml
  - 03-configMap.yaml
  - 04-cronJob.yaml
  - 05-ingress.yaml
  - 06-backendConfig.yaml
  - secrets.yaml
  - todo-db-backup-cronjob.yaml
