apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: server
        image: sirpacoder/server:v1.5
        env:
          - name: PORT
            value: "3001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
