import 'dotenv/config'

const { HASH_FILE_PATH, INFORMATION_FILE_PATH, PING_SERVER_URL, READER_PORT, MESSAGE, GREETER_SERVER_URL } = process.env

export { HASH_FILE_PATH, INFORMATION_FILE_PATH, PING_SERVER_URL, READER_PORT, MESSAGE, GREETER_SERVER_URL }
