version: '3.9'

services:
  log-output:
    image: log-output:v1.7
    container_name: log-output
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    ports:
      - 3001:3001
