apiVersion: v1
data:
    postgres-password: ENC[AES256_GCM,data:5uxLB+1qchGhpUTU,iv:PWn/HvlONRRPf6uMv0fddVApSLaiC4cSNtIZm2C9DAA=,tag:Zgz9wZcbXlQki4H2AEQSvw==,type:str]
kind: Secret
metadata:
    name: project-secret
    namespace: project
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vyhf8zrmtv4uhm8stmh4gxcdrr47yq45qnmtr3ua9a4353tdm30q9we367
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK3ZFVVJtMmYxbThSZEJr
            ZlUybHZ4cncxbjNYMDNPVUhuUUdibnBOSkFjCnM2RWEwWlVSY1c1dDNkWDd0WGpC
            RmYrKzUvRW01UmZVNlZQeHRPRUlEZXcKLS0tIHBhd3poNlNnVmpxbGZ0QUo3ZzdD
            bVpvYks3RHp5ZmJkVFpqVTV6NE5OY1EKvz8DCuWzeww0obcRhDX92wu3sPs63iwH
            gpZvQgtNsydlSj4bbfk4qCFFYGIy2RtXk+RHXP7IckCQ5sqzCErs/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T20:25:16Z"
    mac: ENC[AES256_GCM,data:MPG2z47JmuTogu7hlHgNjbhqz8tK2ifC1jnROzlIjmLMsUk3c1lmsiZWrYN4zADIDlqFeey6JMpLdtMlp3sKlibQBCpPJxZpPoiok//kzvHHxHlxci2yDDEKt2ZfLwb0np7tOYLeyTPTze/NEKmOsdbI1S2z6emuGdMOYabzrx4=,iv:EyAlIlJ5OA4HfHW8HNcVv0GD36v2hrGl+maxlBCBSxs=,tag:nfCZkrSK4bYwqM6OwA/+rw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
