apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: DISCORD_URL
              value: ""
