name: Delete branch environment

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  build-todo-app:
    name: Delete branch
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: Set kubectl to the right cluster
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Delete deployment
        run: |-
          NAMESPACE_NAME=${{ github.event.ref }}
          printf "\033[1;33mDeleting namespace: $NAMESPACE_NAME\033[0m"
          kubectl delete namespace "$NAMESPACE_NAME"
