name: log-output

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: |-
          echo "Tag event ref triggered: ${{ github.event.ref }}"
          echo "Tag ref triggered: ${{ github.ref }}"
