name: Trigger Argo CD Sync on Release Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo CD webhook
        run: |
          curl -X POST http://35.228.167.226/api/webhook
