name: Trigger Argo CD Sync on Release Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'

jobs:
  notify-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo CD webhook
        run: |
          curl -X POST https://suggesting-staff-dealing-layout.trycloudflare.com/api/webhook
